"""empty message

Revision ID: 59291dc822cb
Revises: 
Create Date: 2021-08-24 21:40:41.181941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59291dc822cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
